source 'http://rubygems.org'

gem 'sinatra', '~> 2.1'
gem 'activerecord', '~> 6.1'
gem 'sinatra-activerecord', '~> 2.0'
gem 'rake', '~> 13.0'
gem 'require_all'
gem 'sqlite3', '~> 1.4'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
